appName: servicename
appImage: gcr.io/google-samples/microservices-demo/servicename
appVersion: v0.2.3
appReplicas: 1
containerPort: 8080
containerEnvVars: 
- name: ENV_VAR_ONE
  value: "valueone"
- name: ENV_VAR_TWO
  value: "valuetwo"
- name: ENV_VAR_THREE
  value: "valuethree"
servicePort: 8080
serviceType: ClusterIP